// Automatically generated by astro-icon
// a44aabb0931421b50b89394169096bc0bc3862a8d647ae8abe1faaa6fa6ae51b

declare module 'virtual:astro-icon' {
	export type Icon = 
		| "dribble"
		| "github"
		| "insta"
		| "linkedin"
		| "mail"
		| "phone";
}